/**
 * Auto-generated tool barrel file.
 * Re-exports all tool definitions for registration via navigator.registerTools().
 *
 * Generated by webmcp-extend.
 */
export { getMenuCategoriesTool } from "./getMenuCategories.js";
export { navigateToMenuCategoryTool } from "./navigateToMenuCategory.js";
export { chooseOrderTypeTool } from "./chooseOrderType.js";
export { startOrderTool } from "./startOrder.js";
export { getPageContentTool } from "./getPageContent.js";
export { addDealTool } from "./addDeal.js";
export { viewCartTool } from "./viewCart.js";
export { seeLocalDealsTool } from "./seeLocalDeals.js";

export const allTools = [
  getMenuCategoriesTool,
  navigateToMenuCategoryTool,
  chooseOrderTypeTool,
  startOrderTool,
  getPageContentTool,
  addDealTool,
  viewCartTool,
  seeLocalDealsTool,
] as const;
