/**
 * Tests for export-to-kit.ts — conversion from shim tools to clean starter code.
 */
import { describe, it, expect } from "vitest";
import { exportToKit } from "../../src/generator/export-to-kit.js";
import { generateToolFiles } from "../../src/generator/generate-tools.js";
import type { ToolProposal } from "../../src/analysis/types.js";

const jsCallProposal: ToolProposal = {
  name: "getMenu",
  description: "Get the pizza menu",
  inputSchema: { type: "object", properties: {} },
  actionType: "js-call",
  actionDetails: {
    functionPath: "window.getMenu",
    argMapping: [],
    returnType: "object",
  },
  annotations: { readOnlyHint: true },
};

const domActionProposal: ToolProposal = {
  name: "addToCart",
  description: "Add pizza to cart",
  inputSchema: {
    type: "object",
    properties: {
      id: { type: "string", description: "Pizza ID" },
    },
    required: ["id"],
  },
  actionType: "dom-action",
  actionDetails: {
    steps: [
      { action: "fill", selector: "#pizza-input", inputProperty: "id" },
      { action: "click", selector: "#add-btn" },
    ],
  },
};

describe("exportToKit", () => {
  it("transforms tool file paths from tools/ to webmcp-tools/", () => {
    const files = generateToolFiles([jsCallProposal]);
    const exported = exportToKit(files);

    expect(exported).toHaveLength(1);
    expect(exported[0]?.path).toBe("webmcp-tools/getMenu.ts");
  });

  it("adds header comment about webmcp-extend and webmcp-kit", () => {
    const files = generateToolFiles([jsCallProposal]);
    const exported = exportToKit(files);
    const content = exported[0]!.content;

    expect(content).toContain("Clean starter code generated by webmcp-extend");
    expect(content).toContain("webmcp-kit");
  });

  it("replaces document.querySelector with TODO comments", () => {
    const files = generateToolFiles([domActionProposal]);
    const exported = exportToKit(files);
    const content = exported[0]!.content;

    expect(content).toContain("TODO: Replace DOM query");
    expect(content).not.toContain("document.querySelector");
  });

  it("replaces window function calls with TODO comments", () => {
    const files = generateToolFiles([jsCallProposal]);
    const exported = exportToKit(files);
    const content = exported[0]!.content;

    expect(content).toContain("TODO: Replace window function call");
  });

  it("preserves webmcp-kit imports", () => {
    const files = generateToolFiles([jsCallProposal]);
    const exported = exportToKit(files);
    const content = exported[0]!.content;

    expect(content).toContain("from \"webmcp-kit\"");
    expect(content).toContain("from \"zod\"");
  });

  it("preserves tool name, description, and schema", () => {
    const files = generateToolFiles([jsCallProposal]);
    const exported = exportToKit(files);
    const content = exported[0]!.content;

    expect(content).toContain('"getMenu"');
    expect(content).toContain("Get the pizza menu");
    expect(content).toContain("defineTool");
  });

  it("comments out auto-register", () => {
    const files = generateToolFiles([jsCallProposal]);
    const exported = exportToKit(files);
    const content = exported[0]!.content;

    // Should have a commented-out register call
    expect(content).toContain("// getMenuTool.register()");
  });

  it("removes event dispatch lines", () => {
    const files = generateToolFiles([domActionProposal]);
    const exported = exportToKit(files);
    const content = exported[0]!.content;

    expect(content).not.toContain("dispatchEvent(new Event");
    expect(content).toContain("event dispatch removed");
  });

  it("processes multiple files", () => {
    const files = generateToolFiles([jsCallProposal, domActionProposal]);
    const exported = exportToKit(files);

    expect(exported).toHaveLength(2);
    expect(exported[0]?.path).toBe("webmcp-tools/getMenu.ts");
    expect(exported[1]?.path).toBe("webmcp-tools/addToCart.ts");
  });
});
