/**
 * Content script (MAIN world) — registers auto-generated WebMCP tools
 * via webmcp-kit's defineTool().register() which calls navigator.modelContext.registerTool().
 *
 * Generated by webmcp-extend.
 */

import { defineTool, textContent } from "webmcp-kit";
import { z } from "zod";

// ─── Tool Definitions ──────────────────────────────────────────────────────────

const getMenuCategoriesTool = defineTool({
  name: "getMenuCategories",
  description: "Get the list of available menu categories (e.g., Build Your Own, Specialty Pizzas, Breads, Chicken, Desserts, Pastas, Sandwiches, Salads, Drinks, Extras)",
  inputSchema: z.object({}),
  annotations: { readOnlyHint: true },
  execute: async () => {
    const elements = document.querySelectorAll("a[href^='/menu/']");
    const categories = Array.from(elements).map((el) => el.textContent?.trim()).filter(Boolean);
    return textContent(categories.length > 0 ? categories.join(", ") : "No categories found");
  },
});

const navigateToMenuCategoryTool = defineTool({
  name: "navigateToMenuCategory",
  description: "Navigate to a specific menu category page to browse items (e.g., build-your-own, specialty, bread, tots, wings, dessert, pasta, sandwich, g-salad, drinks, sides)",
  inputSchema: z.object({
    category: z.enum(["build-your-own", "specialty", "bread", "tots", "wings", "dessert", "pasta", "sandwich", "g-salad", "drinks", "sides"]).describe("Menu category slug"),
  }),
  annotations: { readOnlyHint: false },
  execute: async ({ category }) => {
    const el = document.querySelector(`a[href='/menu/${category}']`);
    if (!el) throw new Error(`Element not found: a[href='/menu/${category}']`);
    (el as HTMLElement).click();
    return textContent("Navigated to " + category);
  },
});

const chooseOrderTypeTool = defineTool({
  name: "chooseOrderType",
  description: "Select delivery or carryout order type to begin an order",
  inputSchema: z.object({
    orderType: z.enum(["delivery", "carryout"]).describe("Whether to order for delivery or carryout"),
  }),
  annotations: { readOnlyHint: false },
  execute: async ({ orderType }) => {
    const el = document.querySelector(`a[href='/?type=order_${orderType}']`);
    if (!el) throw new Error(`Element not found: a[href='/?type=order_${orderType}']`);
    (el as HTMLElement).click();
    return textContent("Selected " + orderType);
  },
});

const startOrderTool = defineTool({
  name: "startOrder",
  description: "Click the 'Order Now' button to begin the ordering flow",
  inputSchema: z.object({}),
  annotations: { readOnlyHint: false },
  execute: async () => {
    const el = document.querySelector("button[name='Blue Nav - Order Now']");
    if (!el) throw new Error("Element not found: button[name='Blue Nav - Order Now']");
    (el as HTMLElement).click();
    return textContent("Order started");
  },
});

const getPageContentTool = defineTool({
  name: "getPageContent",
  description: "Read the main content of the current page, useful for reading menu items, pizza options, and prices after navigating to a menu category",
  inputSchema: z.object({}),
  annotations: { readOnlyHint: true },
  execute: async () => {
    await new Promise((resolve) => setTimeout(resolve, 2000));
    const el = document.querySelector("main, #content, [role='main'], .page-content, body");
    return textContent(el?.textContent?.trim() ?? "No content found");
  },
});

const addDealTool = defineTool({
  name: "addDeal",
  description: "Add a promotional deal to the cart (e.g., MixAndMatch, BestDealEver, WeekLongCarryout, PerfectCombo)",
  inputSchema: z.object({
    dealId: z.enum(["MixAndMatch", "BestDealEver", "WeekLongCarryout", "PerfectCombo"]).describe("The deal identifier"),
  }),
  annotations: { readOnlyHint: false },
  execute: async ({ dealId }) => {
    const el = document.querySelector(`#tile-button-${dealId}`);
    if (!el) throw new Error(`Element not found: #tile-button-${dealId}`);
    (el as HTMLElement).click();
    return textContent("Deal added: " + dealId);
  },
});

const viewCartTool = defineTool({
  name: "viewCart",
  description: "Open the shopping cart to view current items",
  inputSchema: z.object({}),
  annotations: { readOnlyHint: true },
  execute: async () => {
    const btn = document.querySelector("button[aria-label^='View cart']");
    if (!btn) throw new Error("Element not found: button[aria-label^='View cart']");
    (btn as HTMLElement).click();
    await new Promise((resolve) => setTimeout(resolve, 1500));
    const panel = document.querySelector("[role='dialog'], .cart-panel, .cart-content, main");
    return textContent(panel?.textContent?.trim() ?? "No content found");
  },
});

const seeLocalDealsTool = defineTool({
  name: "seeLocalDeals",
  description: "View local deals available at the nearest store",
  inputSchema: z.object({}),
  annotations: { readOnlyHint: true },
  execute: async () => {
    const el = document.querySelector("#tile-button-LocalDeals");
    if (!el) throw new Error("Element not found: #tile-button-LocalDeals");
    (el as HTMLElement).click();
    return textContent("Navigated to local deals");
  },
});

// ─── Registration ──────────────────────────────────────────────────────────────

const allTools = [
  getMenuCategoriesTool,
  navigateToMenuCategoryTool,
  chooseOrderTypeTool,
  startOrderTool,
  getPageContentTool,
  addDealTool,
  viewCartTool,
  seeLocalDealsTool,
];

console.log("[webmcp-extend] Registering tools via webmcp-kit...");
for (const tool of allTools) {
  tool.register();
}
console.log(`[webmcp-extend] Registered ${allTools.length} tool(s):`, allTools.map((t) => t.name));

// ─── Nudge Banner ──────────────────────────────────────────────────────────────

function injectNudgeBanner(): void {
  const dismissed = localStorage.getItem("webmcp-extend-banner-dismissed");
  if (dismissed === "true") return;

  const banner = document.createElement("div");
  banner.id = "webmcp-extend-nudge";
  banner.innerHTML = `
    <div style="
      position: fixed;
      bottom: 16px;
      right: 16px;
      z-index: 2147483647;
      background: #1a1a2e;
      color: #e0e0e0;
      padding: 12px 16px;
      border-radius: 8px;
      font-family: system-ui, -apple-system, sans-serif;
      font-size: 13px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.3);
      display: flex;
      align-items: center;
      gap: 8px;
      max-width: 380px;
      border: 1px solid #333;
    ">
      <span style="flex: 1;">
        🔧 Tools auto-generated by <strong>webmcp-extend</strong>.
        <a href="https://github.com/victorhuangwq/webmcp-kit"
           target="_blank"
           style="color: #64b5f6; text-decoration: none;">
          Go native with webmcp-kit →
        </a>
      </span>
      <button id="webmcp-extend-dismiss" style="
        background: none;
        border: none;
        color: #888;
        cursor: pointer;
        font-size: 16px;
        padding: 0 4px;
        line-height: 1;
      ">✕</button>
    </div>
  `;
  document.body.appendChild(banner);

  document.getElementById("webmcp-extend-dismiss")?.addEventListener("click", () => {
    banner.remove();
    localStorage.setItem("webmcp-extend-banner-dismissed", "true");
  });
}

// ─── Lifecycle ─────────────────────────────────────────────────────────────────

window.addEventListener("beforeunload", () => {
  console.log("[webmcp-extend] Page unloading — unregistering tools");
  for (const tool of allTools) {
    tool.unregister();
  }
});

injectNudgeBanner();
