/**
 * Nudge banner — a small, dismissible prompt encouraging developers
 * to migrate from auto-generated tools to native webmcp-kit.
 *
 * This module can be used standalone (injected by the extension)
 * or imported from the content script.
 *
 * Generated by webmcp-extend.
 */

const BANNER_ID = "webmcp-extend-nudge-banner";
const DISMISS_KEY = "webmcp-extend-banner-dismissed";

/**
 * Show the nudge banner, if not previously dismissed.
 */
export function showNudgeBanner(): void {
  // Don't show if already dismissed
  if (localStorage.getItem(DISMISS_KEY) === "true") return;

  // Don't show if already present
  if (document.getElementById(BANNER_ID)) return;

  const banner = document.createElement("div");
  banner.id = BANNER_ID;
  banner.setAttribute("role", "status");
  banner.setAttribute("aria-live", "polite");

  // Style the banner
  Object.assign(banner.style, {
    position: "fixed",
    bottom: "16px",
    right: "16px",
    zIndex: "2147483647",
    background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
    color: "#e0e0e0",
    padding: "14px 18px",
    borderRadius: "10px",
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: "13px",
    lineHeight: "1.5",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.35)",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    maxWidth: "400px",
    border: "1px solid rgba(100, 181, 246, 0.2)",
    transition: "opacity 0.3s ease, transform 0.3s ease",
    transform: "translateY(0)",
    opacity: "1",
  });

  // Create content
  const content = document.createElement("span");
  content.style.flex = "1";
  content.innerHTML = `
    🔧 These tools are auto-generated by <strong style="color: #90caf9;">webmcp-extend</strong>.
    Build production-grade tools with
    <a href="https://github.com/victorhuangwq/webmcp-kit"
       target="_blank"
       rel="noopener noreferrer"
       style="color: #64b5f6; text-decoration: none; font-weight: 600;">
      webmcp-kit →
    </a>
  `;

  // Create dismiss button
  const dismissBtn = document.createElement("button");
  Object.assign(dismissBtn.style, {
    background: "none",
    border: "none",
    color: "#888",
    cursor: "pointer",
    fontSize: "16px",
    padding: "2px 6px",
    lineHeight: "1",
    borderRadius: "4px",
    transition: "color 0.2s, background 0.2s",
  });
  dismissBtn.textContent = "✕";
  dismissBtn.title = "Dismiss";
  dismissBtn.setAttribute("aria-label", "Dismiss webmcp-extend banner");

  dismissBtn.addEventListener("mouseenter", () => {
    dismissBtn.style.color = "#fff";
    dismissBtn.style.background = "rgba(255,255,255,0.1)";
  });
  dismissBtn.addEventListener("mouseleave", () => {
    dismissBtn.style.color = "#888";
    dismissBtn.style.background = "none";
  });

  dismissBtn.addEventListener("click", () => {
    banner.style.opacity = "0";
    banner.style.transform = "translateY(10px)";
    setTimeout(() => banner.remove(), 300);
    localStorage.setItem(DISMISS_KEY, "true");
  });

  banner.appendChild(content);
  banner.appendChild(dismissBtn);
  document.body.appendChild(banner);
}

/**
 * Hide and remove the nudge banner, if visible.
 */
export function hideNudgeBanner(): void {
  const banner = document.getElementById(BANNER_ID);
  if (banner) {
    banner.style.opacity = "0";
    banner.style.transform = "translateY(10px)";
    setTimeout(() => banner.remove(), 300);
  }
}

/**
 * Reset the banner dismissal (for testing).
 */
export function resetNudgeBanner(): void {
  localStorage.removeItem(DISMISS_KEY);
}

// Auto-show when injected as a standalone script
if (typeof document !== "undefined" && document.readyState !== "loading") {
  showNudgeBanner();
} else if (typeof document !== "undefined") {
  document.addEventListener("DOMContentLoaded", showNudgeBanner);
}
