/**
 * Export-to-kit conversion — transforms auto-generated shim tools
 * into clean, idiomatic webmcp-kit starter code.
 *
 * Strips DOM selectors and window.* calls, replacing them with TODO
 * comments that guide the developer toward proper app-state integration.
 */
import type { GeneratedFile } from "../analysis/types.js";

/**
 * Convert generated shim tools into clean webmcp-kit starter code.
 *
 * @param toolFiles - The auto-generated tool files from generate-tools.
 * @returns New files with DOM selectors stripped and TODO comments added.
 */
export function exportToKit(toolFiles: GeneratedFile[]): GeneratedFile[] {
  return toolFiles.map((file) => ({
    path: file.path.replace("tools/", "webmcp-tools/"),
    content: transformToKitCode(file.content),
  }));
}

/**
 * Transform a single generated tool file into clean kit starter code.
 */
function transformToKitCode(content: string): string {
  let result = content;

  // Add header comment
  result = `/**
 * WebMCP Tool — Clean starter code generated by webmcp-extend.
 *
 * This file was exported from an auto-generated shim tool.
 * Replace the TODO comments with your own application logic.
 *
 * Docs: https://github.com/nicholasgriffintn/webmcp-kit
 */
${result}`;

  // Replace document.querySelector calls with TODO comments
  result = result.replace(
    /const (\w+) = document\.querySelector\(([^)]+)\);/g,
    (_match, varName: string, selector: string) =>
      `// TODO: Replace DOM query with your app's state or API\n    // Original selector: ${selector}\n    const ${varName} = null; // your-app.getElement() or your-app.getData()`,
  );

  // Replace element .click() calls
  result = result.replace(
    /\((\w+) as HTMLElement\)\.click\(\);/g,
    (_match, varName: string) =>
      `// TODO: Replace DOM click with your app's action handler\n    // ${varName}.click() → your-app.performAction()`,
  );

  // Replace input .value = assignments
  result = result.replace(
    /\((\w+) as HTMLInputElement\)\.value = ([^;]+);/g,
    (_match, varName: string, value: string) =>
      `// TODO: Replace DOM input with your app's state setter\n    // ${varName}.value = ${value} → your-app.setValue(${value})`,
  );

  // Replace select .value = assignments
  result = result.replace(
    /\((\w+) as HTMLSelectElement\)\.value = ([^;]+);/g,
    (_match, varName: string, value: string) =>
      `// TODO: Replace DOM select with your app's state setter\n    // ${varName}.value = ${value} → your-app.setSelection(${value})`,
  );

  // Replace form .submit() calls
  result = result.replace(
    /\((\w+) as HTMLFormElement\)\.submit\(\);/g,
    (_match, varName: string) =>
      `// TODO: Replace form submission with your app's submit handler\n    // ${varName}.submit() → your-app.submitForm(input)`,
  );

  // Replace dispatchEvent calls
  result = result.replace(
    /\w+\.dispatchEvent\(new Event\([^)]+\)\);/g,
    "// (event dispatch removed — handle state changes in your app logic)",
  );

  // Replace window.* function calls
  result = result.replace(
    /const fn = (window\.\w+(?:\.\w+)*);/g,
    (_match, fnPath: string) =>
      `// TODO: Replace window function call with your app's API\n    // Original: ${fnPath}\n    const fn = null; // your-app.yourMethod`,
  );

  // Replace error messages referencing selectors
  result = result.replace(
    /throw new Error\("Element not found: [^"]+"\);/g,
    `throw new Error("TODO: Implement this action using your app's API");`,
  );

  // Replace "Action completed successfully" with guidance
  result = result.replace(
    /return textContent\("Action completed successfully"\);/g,
    `return textContent("Success"); // TODO: Return meaningful result from your app`,
  );

  // Remove the auto-register line and add a note
  result = result.replace(
    /\/\/ Register the tool when this module is loaded\n\w+Tool\.register\(\);\n/g,
    `// Register the tool — call this from your app's initialization
// ${getToolNameFromContent(content)}Tool.register();
`,
  );

  return result;
}

/**
 * Extract the tool variable name from generated content.
 */
function getToolNameFromContent(content: string): string {
  const match = content.match(/export const (\w+)Tool/);
  return match?.[1] ?? "myTool";
}
